### ISSUE TITLE
Website bugs

### ISSUE THREAD

**Issue by mmf6** [borisbabic/d0nkey.top#19]
Rank error display.
Please fix this bug if you can.
![屏幕截图 2024-01-07 080853](https://github.com/borisbabic/d0nkey.top/assets/155899843/79002394-5925-4d6c-acd9-4e0ae0155720)
![屏幕截图 2024-01-07 081102](https://github.com/borisbabic/d0nkey.top/assets/155899843/83ee0af7-7b48-4b2b-9e5a-657ca36e09cb)

**Comment by borisbabic** [comment]
Hi, it doesn't look like a bug to me, but rather that there are multiple people called mmf on the leaderboards. Unfortunately I don't get the full battletag from the leaderboards api, so I can't differentiate between multiple people called the same.

On the page in the first pic you can use the max rank filter to manually ignore such entries.
