### ISSUE TITLE
Localization deployment service failure: First run

### ISSUE THREAD

**Issue by sssssch** [borisbabic/d0nkey.top#20]
Hi,
I seem to be running into an environmental problem, using the command mix reports an error when I install dependencies.

-> # mix deps.get                     
** (RuntimeError) environment variable BNET_CLIENT_ID is missing.
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:449: :erl_eval.expr/5
    (stdlib) erl_eval.erl:126: :erl_eval.exprs/5
    (elixir) lib/code.ex:240: Code.eval_string/3
    (elixir) lib/config.ex:219: Config.__eval__!/2
    (mix) lib/mix/tasks/loadconfig.ex:38: Mix.Tasks.Loadconfig.load/1
    (mix) lib/mix/tasks/loadconfig.ex:28: Mix.Tasks.Loadconfig.run/1

Since I have never dealt with mix as well as elixir, this question makes me clueless.
Thanks.
PS: Can you provide a completely docker-based deployment method, much appreciated!

**Comment by borisbabic** [comment]
You're missing the `BNET_CLIENT_ID` environment variable. The readme hasn't been updated with all environment variables that are necessary.

**Comment by sssssch** [comment]
Hi，
Thanks for your reply. "Are you looking to deploy it elsewhere and change the code so it's translated?" -Yes, I'm trying to deploy it on my cloud server and I really like hsguru. But for the past two weeks I can't access it properly (502 Bad Gate).

**Comment by borisbabic** [comment]
You've been getting the 502 cloudflare error for the past 2 weeks? I did some infrastructure upgrades ~10 days ago and you shouldn't be getting those issues anymore. 

I don't think a second deployment is the way to go for translating, and if you deployed the code again that wouldn't give you access to the data my site has.

What language did you want to translate it into?

**Comment by sssssch** [comment]
Hi,

I would like to try to deploy the project without changes first.

"and if you deployed the code again that wouldn't give you access to the data my site has."
Why can't I access your website data? Is this project a front-end project, which means it doesn't include data sources (back-end)?

Thanks!

**Comment by borisbabic** [comment]
The data is in a database. If you deployed this codebase that would not grant you access to my database.

If the goal is just that you want to translate it, it would be better to enable translations in my deployment. What language are you interested in translating it into?

**Comment by sssssch** [comment]
Hi,

"What language are you interested in translating it into?" -My tech stack leans a bit towards the backend, with some knowledge of Vue.js, but nowhere near enough to rewrite the project.

PS Is the database part open source yet?

**Comment by borisbabic** [comment]
Hi, there may be a miscommunication. I'm not talking about rewriting it in a different programming language, but translating it into another language besides English. I thought that is what you wanted to accomplish.


> PS Is the database part open source yet?

In this repo you have all the code for setuping the schema and communicating with _a_ database, so in that way the database part is open source. However, this repo does not include access information for the specific database that my site uses. That is not something that's supposed to be open and public. Stuff like that and passwords for things like battlenet aren't supposed to be public and shared with everybody. You can provide them via environment variables for your specific deployment. 


If you want to deploy a copy of this website you will need to spin up your own database.

**Comment by sssssch** [comment]
Hi，

My original intent was to see how d0nkey got the Hearthstone user data, but that kind of information really can't be made public.

However, if you would like me to make some translations of the d0nkey webpage, I would be happy to do so. For me, I can translate the site from English to Chinese.

**Comment by sssssch** [comment]
Hi，

"My site gets the data from Firestone or from my HDT plugin. In both cases the deck tracker sends the data to my site. " - I'm working on the Hearthstone channel bot. Thanks for the info!

"Unfortunately, I don't currently have support for translating my website, it's something I want to do." - I'll be happy to provide support after you've developed this feature.
