### ISSUE TITLE
Cards with the same name but from different sets should not be counted as separate cards

### ISSUE THREAD

**Issue by marlonrichert** [borisbabic/d0nkey.top#54]
For example, look at [Jade Rogue](https://www.hsguru.com/card-stats?archetype=Jade+Rogue&format=4&min_drawn_count=25&min_mull_count=200&period=past_week&rank=all&show_counts=yes&sort_by=drawn_impact&sort_direction=desc). It makes no sense to treat both editions of Jade Swarmer, Jade Shuriken, etc. as separate cards. They both function exactly the same and count towards the same card limit.

Not only doesn't it make sense, it messes up the stats. Multiple editions of the same card should be combined to determine impact, not treated separately. Many decks quite randomly use whichever edition of the same card. That does not make them function differently.

**Comment by borisbabic** [comment]
This shouldn't be happening, thanks for the report, I'll look into it.

**Comment by borisbabic** [comment]
The official api has doubled text for jade golem Caverns of Time cards which threw off how I recognize that two cards are interchangeable

![image](https://github.com/user-attachments/assets/b1d72d0c-b3ab-40c4-b4fa-2e8ec606df82)

**Comment by borisbabic** [comment]
This should be fixed now. There is a bug in the official api/website with how Caverns of Times jade golem cards having duplicated card text. That threw off how I recognize that two cards are interchangeable. I added a workaround which should resolve the issue
